apiVersion: apps/v1
kind: Deployment
metadata:
  name: buscador
spec:
  selector:
    matchLabels:
      app: buscador
  template:
    metadata:
      labels:
        app: buscador
    spec:
      containers:
      - name: buscador
        image: alessandrocb/buscador-de-repositorios
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
