apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculadora
spec:
  selector:
    matchLabels:
      name: calculadora
  template:
    metadata:
      name: calculadora
      labels:
        app: calculadora
        name: calculadora
    spec:
      containers:
      - name: calculadora
        image: momanhaes/calculadora:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
