apiVersion: v1
kind: Service
metadata:
  name: calculadora-service
spec:
  selector:
    app: calculadora
  ports:
  - port: 3030
    protocol: TCP
    targetPort: 80
  type: NodePort
  externalIPs:
    - 172.18.65.53
